feat: Make `chain_id` configurable for L2 Network
hirosystems/stacks-hyperchains pull request #119
Opened 2022-06-16 20:37 UTC by gregorycoppola

### Description
With this change, we make it so that `chain_id` is a field in `NodeConfig`, analogous to `chain_id` for `BurnchainConfig`.

`chain_id` for L2 is also the "network id", so it is also analogous to `network_id` in `BurnchainConfig`.

### Applicable issues
- fixes #112

### Checklist
- [ ] Test coverage for new or modified code paths

2022-06-17 19:08 UTC, kantai requested changes
~~This PR appears to be changing the chain parameters of the burnchain (the L1 network), rather than then L2 network. The chain parameters of the burnchain should not be changed by this PR: those are constants associated with the L1 network (which hyperchains do not alter). Instead, this PR should be altering the chain identifier and network identifier for the layer 2 node (controlled, e.g., by the `StacksChainState` initialization.~~

Nevermind -- I think I was reading this PR incorrectly.

2022-06-17 19:14 UTC, kantai commented on src/burnchains/mod.rs
> +            chain_id: LAYER_1_CHAIN_ID_MAINNET,
This should be `TESTNET`

2022-06-17 19:14 UTC, kantai commented on src/burnchains/mod.rs
> +            chain_id: LAYER_1_CHAIN_ID_MAINNET,
This should be `TESTNET` as well.

2022-06-17 19:16 UTC, kantai commented on testnet/stacks-node/src/config.rs
> +    /// u32-valued index of the chain. This is also the `network_id` for L2.
It's not an index -- it's an identifier.

2022-06-17 19:16 UTC, kantai commented on testnet/stacks-node/src/config.rs
>      pub chain_id: u32,
This is the chain identifier of the burnchain.

2022-06-17 19:16 UTC, kantai commented on testnet/stacks-node/src/config.rs
> +    /// Indexes into the networking code.
This is the burnchain's network identifier

2022-06-17 19:18 UTC, kantai commented on testnet/stacks-node/src/tests/neon_integrations.rs
> +    error!("Using random L2 chain_id {}", conf.node.chain_id);
Can you add this random identifier to the `new_test_conf()` constructor? That way it'll be used in all tests. Also, I think this should be an `info` log rather than `error!`

2022-06-17 19:19 UTC, kantai reviewed
This looks good to me, but I'd like to see the chain identifier randomization in all the integration tests

2022-06-21 16:03 UTC, gregorycoppola commented on src/burnchains/mod.rs
> +            chain_id: LAYER_1_CHAIN_ID_MAINNET,
done

2022-06-21 16:04 UTC, gregorycoppola commented on testnet/stacks-node/src/config.rs
> +    /// Indexes into the networking code.
ok

2022-06-22 23:44 UTC, gregorycoppola commented
adding @pavitthrap as reviewer in case we want to approve this this week

but if there's no urgency you can just let @kantai finish his review

2022-06-29 21:45 UTC, kantai approved these changes
This looks good to me -- just make sure that the tests continue to pass after updating from `master`

2022-07-07 13:05 UTC, merged