test: add mining benchmarks
hirosystems/stacks-hyperchains pull request #236
Opened 2023-03-10 15:08 UTC by obycode

Adds tests to benchmark the time to build a full block (2MB size limit only) and to test building a block in 15s. For each, there is one test that uses STX transfers only, and one that uses a random mixture of NFT mints, NFT transfers, and STX transfers. The mempool is loaded up with transactions first, then the block is mined.

2023-07-11 15:51 UTC, jbencin requested changes
This needs doc comments explaining what each test measures, how it works, what expected output is, etc.

2023-07-13 18:05 UTC, jbencin requested changes

2023-07-13 18:05 UTC, jbencin commented on src/chainstate/stacks/bench.rs
> +    ///   cargo test --package stacks-subnets --lib -- chainstate::stacks::bench::tests::test_max_block --exact --nocapture --ignored
Doc comments are rendered as Markdown by `cargo doc`, so use appropriate syntax. Same for other comments:

```suggestion
    /// ```
    ///   Miner: mined anchored block, block_hash: 5c259637d326c86bac17900d07f4d0d38b8cf5b854b6898bdf51017c2cab6461,
    ///     height: 2,   tx_count: 10567, parent_stacks_block_hash: 34553785fcaa07bb07cf3341e30c18ba390381591f10e502f27c346c50d00cf7,
    ///     parent_stacks_microblock: 0000000000000000000000000000000000000000000000000000000000000000,
    ///     parent_stacks_microblock_seq:    0, block_size: 2097103,
    ///     execution_consumed: {"runtime": 22269784000, "write_len": 82452, "write_cnt": 12916, "read_len": 17205312, "read_cnt": 42972},
    ///     assembly_time_ms: 99140, tx_fees_microstacks: 18138000
    /// ```
    /// where the interesting fields are `assembly_time_ms` and `tx_count`.
    ///
    /// To run this test:
    /// ```sh
    /// cargo test --package stacks-subnets --lib -- chainstate::stacks::bench::tests::test_max_block --exact --nocapture --ignored
    /// ```
```

2023-07-13 18:48 UTC, obycode commented on src/chainstate/stacks/bench.rs
> +    ///   cargo test --package stacks-subnets --lib -- chainstate::stacks::bench::tests::test_max_block --exact --nocapture --ignored
Good point. Added.

2023-07-13 18:56 UTC, jbencin approved these changes

2023-07-14 16:21 UTC, merged

2023-07-17 22:41 UTC, blockstack-devops commented
:tada: This PR is included in version 0.8.1 :tada:

The release is available on [GitHub release](https://github.com/hirosystems/stacks-subnets/releases/tag/v0.8.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: